v1Functions = []
v2Functions = [#"a2-checker-values-lang", 
"uniquify", 
"sequentialize-let",
 "normalize-bind",
 "select-instructions",
"assign-homes",
 "flatten-begins",
 "patch-instructions",
 "implement-fvars",
 "a2-checker-paren-x64",
 "generate-x64",
 "wrap-x64-boilerplate",
 "values",
 ]
v3Functions = [#"a3-checker-values-lang", 
"uniquify", 
"sequentialize-let",
 "normalize-bind",
 "select-instructions",
 "uncover-locals",
 "assign-fvars",
 "replace-locations",
"assign-homes",
 "flatten-begins",
 "patch-instructions",
 "implement-fvars",
#  "a2-checker-paren-x64",
 "generate-x64",
 "wrap-x64-boilerplate",
 "values",
 ]
v4Functions = [#"a2-checker-values-lang", 
"uniquify", 
"sequentialize-let",
 "normalize-bind",
 "select-instructions",
 "uncover-locals",
 "undead-analysis",
 "conflict-analysis",
 "assign-registers",
 "replace-locations",
"assign-homes",
"optimize-predicates",
"expose-basic-blocks",
"resolve-predicates",
 "flatten-program",
 "patch-instructions",
 "implement-fvars",
#  "a2-checker-paren-x64",
 "generate-x64",
 "wrap-x64-boilerplate",
 "values",
 ]
v5Functions = []
v6Functions = ["check-values-lang", 
"uniquify", 
"sequentialize-let",
 "normalize-bind",
 "impose-calling-conventions",
 "select-instructions",
 "uncover-locals",
 "undead-analysis",
 "conflict-analysis",
 "assign-call-undead-variables",
 "allocate-frames",
 "assign-registers",
 "assign-frame-variables",
 "replace-locations",
 "optimize-predicates",
 "implement-fvars",
 "expose-basic-blocks",
 "resolve-predicates",
 "flatten-program",
 "patch-instructions",
 "generate-x64",
 "wrap-x64-boilerplate",
 "values",
 ]
v7Functions = []
v8Functions = []
v9Functions = []
v10Functions = []

# Output function order for V6
functions = [v1Functions, v2Functions, 
v3Functions, v4Functions, v5Functions,
v6Functions, v7Functions, v8Functions, 
v9Functions, v10Functions]